<label for="">Status</label>
<select class="form-control" name="published">
    @if(isset($article->id))
        <option value="0" @if($article-> published == 0) selected="" @endif> Not published</option>
        <option value="1" @if($article-> published == 1) selected="" @endif> Published</option>
    @else
        <option value="0"> Not published</option>
        <option value="1"> Published</option>
    @endif
</select>

<label for="">Title</label>
<input class="form-control" type="text" name="title" placeholder="Title"
       value="{{$article->title ?? ""}}" required>

<label for="">Slug</label>
<input class="form-control" type="text" name="slug" placeholder="Slug autogenerated"
       value="{{$article->slug ?? ""}}" readonly="">

<label for="">Category</label>
<select class="form-control" name="categories[]" multiple="multiple">
    <option value="0"> -- without parent category -- </option>
    @include('admin.articles.partials.categories')
</select>

<label for=""> Short description article</label>
<textarea class="form-control" id="description_short" name="description_short">{{$article->description_short ?? ""}}</textarea>

<label for=""> Short description article</label>
<textarea class="form-control" id="description" name="description">{{$article->description ?? ""}}</textarea>
<hr />


<label for="">Meta title</label>
<input class="form-control" type="text" name="meta_title" placeholder="Meta title"
       value="{{$article->meta_title ?? ""}}">

<label for="">Meta description</label>
<input class="form-control" type="text" name="meta_description" placeholder="Meta description"
       value="{{$article->meta_description ?? ""}}">

<label for="">Keywords</label>
<input class="form-control" type="text" name="meta_keyword" placeholder="Keywords through a comma"
       value="{{$article->meta_keyword ?? ""}}">
<hr />
<input class="btn btn-primary" type="submit" value="Сохранить">
